//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR_SB_GK_Acad.Model.ExportColorIndex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_nn_Item_Tier
    {
        public decimal ItemTierId { get; set; }
        public Nullable<decimal> ItemId { get; set; }
        public Nullable<decimal> TierId { get; set; }
    
        public virtual I_C_Tier I_C_Tier { get; set; }
        public virtual I_R_Item I_R_Item { get; set; }
    }
}
