//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR_SB_GK_Acad.Model.ExportColorIndex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_S_Side
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_S_Side()
        {
            this.I_S_BalconyCut = new HashSet<I_S_BalconyCut>();
        }
    
        public decimal SideId { get; set; }
        public string Side { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_S_BalconyCut> I_S_BalconyCut { get; set; }
    }
}
