//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR_SB_GK_Acad.Model.ExportColorIndex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_S_ItemGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_S_ItemGroup()
        {
            this.I_R_Item = new HashSet<I_R_Item>();
        }
    
        public decimal ItemGroupId { get; set; }
        public bool ItemGroupUsage { get; set; }
        public string ItemGroup { get; set; }
        public Nullable<decimal> ItemGroupLongId { get; set; }
        public string ItemGroupTextISO { get; set; }
        public Nullable<decimal> BuildingPartId { get; set; }
        public string ItemGroupISO { get; set; }
        public string ItemDescription { get; set; }
        public string ItemGroupStatic { get; set; }
        public string ItemGroupCut { get; set; }
        public string ItemGroupLayer { get; set; }
    
        public virtual I_C_BuildingPart I_C_BuildingPart { get; set; }
        public virtual I_C_ItemGroupLong I_C_ItemGroupLong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_R_Item> I_R_Item { get; set; }
    }
}
